BBLAYERS ?= " \
  /home/alin/UbuntuInterview/bootable-linux-test/bitbake-builds/poky-master/layers/openembedded-core/meta \
  /home/alin/UbuntuInterview/bootable-linux-test/bitbake-builds/poky-master/layers/meta-yocto/meta-yocto-bsp \
  /home/alin/UbuntuInterview/bootable-linux-test/bitbake-builds/poky-master/layers/meta-yocto/meta-poky \
  /home/alin/UbuntuInterview/bootable-linux-test/bitbake-builds/poky-master/layers/meta-yocto/meta-custom \
  "
