#
# This file is intended for local configuration tweaks.
#
# If you would like to publish and share changes made to this file,
# it is recommended to put them into a distro config, or to create
# layer fragments from changes made here.
#
PREFERRED_PROVIDER_virtual/kernel = "linux-kernel-custom"
PREFERRED_PROVIDER_linux-qemux86-64 = "linux-kernel-custom"
EXTRA_IMAGE_FEATURES += "serial-autologin-root"
MACHINE = "qemux86-64"

IMAGE_FSTYPES += "wic"
WKS_FILE = "directdisk.wks"
